/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 src/assets/baby-habitmon.glb --types --output src/threeJS/meshes/Baby.tsx 
*/

import * as THREE from 'three'
import type { ThreeElements } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'
import babyUrl from '../../assets/baby-habitmon.glb?url'

type GLTFResult = GLTF & {
  nodes: {
    body: THREE.Mesh
  }
  materials: {
    body: THREE.MeshStandardMaterial
  }
}

export function Baby(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF(babyUrl) as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.body.geometry} material={materials.body} />
    </group>
  )
}

useGLTF.preload(babyUrl)
