/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import type { ThreeElements } from '@react-three/fiber'
import * as THREE from 'three'
import type { GLTFResult } from './types/ForestTypes'

export function Forest(props: ThreeElements['group']) {
  const group = useRef<THREE.Group>(null)
  const { nodes, materials, animations } = useGLTF('/src/assets/test_forest.glb') as unknown as GLTFResult
  useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.001}>
          <group name="69b8f327d21547778fe4aadf88c8a8a3fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group
                  name="bismo_small"
                  position={[-2532.338, 1915.536, 890.102]}
                  rotation={[-1.74, -0.038, -2.1]}
                  scale={2.034}>
                  <mesh
                    name="bismo_small_Material001_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.bismo_small_Material001_0.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group
                  name="bismo_small_Eye1"
                  position={[-2552.771, 2083.339, 856.352]}
                  scale={100}>
                  <mesh
                    name="bismo_small_Eye1_Default-Material_0"
                    castShadow
                    receiveShadow
                    geometry={nodes['bismo_small_Eye1_Default-Material_0'].geometry}
                    material={materials['Default-Material']}
                  />
                </group>
                <group
                  name="bismo_small_Eye2"
                  position={[-2551.623, 2078.825, 837.655]}
                  rotation={[-1.633, 0.043, -1.311]}
                  scale={[2.259, 3.163, 3.163]}>
                  <mesh
                    name="bismo_small_Eye2_character_eyes_BIGblue_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.bismo_small_Eye2_character_eyes_BIGblue_0.geometry}
                    material={materials.character_eyes_BIGblue}
                  />
                </group>
                <group
                  name="canyon_mountains02_(3)"
                  position={[-745.648, 1688.95, 2027.125]}
                  scale={100}>
                  <mesh
                    name="canyon_mountains02_(3)_rock_0"
                    castShadow
                    receiveShadow
                    geometry={nodes['canyon_mountains02_(3)_rock_0'].geometry}
                    material={materials.rock}
                  />
                </group>
                <group
                  name="Cube"
                  position={[-2516.097, 1774.773, -77.205]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}>
                  <mesh
                    name="Cube_forest_leaves_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube_forest_leaves_0.geometry}
                    material={materials.forest_leaves}
                  />
                </group>
                <group
                  name="Field"
                  position={[-2292.448, 4266.97, -984.94]}
                  rotation={[2.606, -1.027, -2.173]}
                  scale={100}
                />
                <group
                  name="forest_fox_sleeping"
                  position={[-2466.011, 1712.366, 647.896]}
                  scale={100}>
                  <mesh
                    name="forest_fox_sleeping_fox_white_new_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.forest_fox_sleeping_fox_white_new_0.geometry}
                    material={materials.fox_white_new}
                  />
                </group>
                <group
                  name="forest_grass_03_(9)"
                  position={[-3773.385, 1639.83, -413.275]}
                  scale={100}>
                  <mesh
                    name="forest_grass_03_(9)_grass_0"
                    castShadow
                    receiveShadow
                    geometry={nodes['forest_grass_03_(9)_grass_0'].geometry}
                    material={materials.grass}
                  />
                </group>
                <group name="particle000" position={[-3540.313, 2387.311, -65.243]} scale={0}>
                  <mesh
                    name="particle000_leaves_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.particle000_leaves_0.geometry}
                    material={materials.leaves}
                    position={[16, 0, -0.25]}
                    scale={0}
                  />
                </group>
                <group
                  name="particle001"
                  position={[-3062.302, 2306.122, -24.811]}
                  rotation={[-3.037, -0.569, -0.495]}
                  scale={11.465}>
                  <mesh
                    name="particle001_leaves_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.particle001_leaves_0.geometry}
                    material={materials.leaves}
                  />
                </group>
                <group
                  name="particle002"
                  position={[-1301.395, 1943.477, 1258.118]}
                  rotation={[0.462, 1.074, -2.724]}
                  scale={65.187}>
                  <mesh
                    name="particle002_leaves_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.particle002_leaves_0.geometry}
                    material={materials.leaves}
                  />
                </group>
                <group
                  name="particle003"
                  position={[-562.424, 1963.369, 643.486]}
                  rotation={[-2.098, -0.376, -2.65]}
                  scale={66.927}>
                  <mesh
                    name="particle003_leaves_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.particle003_leaves_0.geometry}
                    material={materials.leaves}
                  />
                </group>
                <group
                  name="particle004"
                  position={[-731.057, 2149.237, 773.974]}
                  rotation={[1.004, -0.432, -1.068]}
                  scale={142.426}>
                  <mesh
                    name="particle004_leaves_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.particle004_leaves_0.geometry}
                    material={materials.leaves}
                  />
                </group>
                <group
                  name="particle005"
                  position={[-1645.595, 2493.266, -1339.309]}
                  rotation={[-2.115, 0.525, -2.951]}
                  scale={173.126}>
                  <mesh
                    name="particle005_leaves_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.particle005_leaves_0.geometry}
                    material={materials.leaves}
                  />
                </group>
                <group
                  name="particle006"
                  position={[-3198.167, 2396.824, -149.246]}
                  rotation={[1.343, -0.84, 1.854]}
                  scale={118.36}>
                  <mesh
                    name="particle006_leaves_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.particle006_leaves_0.geometry}
                    material={materials.leaves}
                  />
                </group>
                <group
                  name="particle007"
                  position={[-1102.205, 2224.853, 1055.982]}
                  rotation={[-2.058, 0.183, -0.008]}
                  scale={128.57}>
                  <mesh
                    name="particle007_leaves_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.particle007_leaves_0.geometry}
                    material={materials.leaves}
                  />
                </group>
                <group
                  name="particle008"
                  position={[-948.5, 2238.101, 439.216]}
                  rotation={[1.698, -0.88, 2.198]}
                  scale={139.639}>
                  <mesh
                    name="particle008_leaves_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.particle008_leaves_0.geometry}
                    material={materials.leaves}
                  />
                </group>
                <group
                  name="particle009"
                  position={[-3082.885, 2544.469, -391.853]}
                  rotation={[1.95, -1.144, 2.036]}
                  scale={196.227}>
                  <mesh
                    name="particle009_leaves_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.particle009_leaves_0.geometry}
                    material={materials.leaves}
                  />
                </group>
                <group
                  name="particle010"
                  position={[-1303.308, 2222.801, 1329.278]}
                  rotation={[0.728, -0.891, 0.134]}
                  scale={233.12}>
                  <mesh
                    name="particle010_leaves_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.particle010_leaves_0.geometry}
                    material={materials.leaves}
                  />
                </group>
                <group
                  name="particle011"
                  position={[-2596.479, 2698.962, 392.372]}
                  rotation={[-0.969, -0.751, 0.533]}
                  scale={124.14}>
                  <mesh
                    name="particle011_leaves_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.particle011_leaves_0.geometry}
                    material={materials.leaves}
                  />
                </group>
                <group
                  name="particle012"
                  position={[-2989.379, 2549.619, -118.847]}
                  rotation={[-1.766, -0.287, -1.675]}
                  scale={201.002}>
                  <mesh
                    name="particle012_leaves_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.particle012_leaves_0.geometry}
                    material={materials.leaves}
                  />
                </group>
                <group
                  name="particle013"
                  position={[-619.34, 2402.844, 1520.814]}
                  rotation={[-2.032, -1.11, 2.012]}
                  scale={227.469}>
                  <mesh
                    name="particle013_leaves_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.particle013_leaves_0.geometry}
                    material={materials.leaves}
                  />
                </group>
                <group
                  name="particle014"
                  position={[-1136.484, 2436.005, 1162.334]}
                  rotation={[-0.973, -0.519, -2.306]}
                  scale={243.343}>
                  <mesh
                    name="particle014_leaves_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.particle014_leaves_0.geometry}
                    material={materials.leaves}
                  />
                </group>
                <group
                  name="particle015"
                  position={[-2337.003, 2807.106, -114.136]}
                  rotation={[0.04, -0.075, 0.551]}
                  scale={130.915}>
                  <mesh
                    name="particle015_leaves_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.particle015_leaves_0.geometry}
                    material={materials.leaves}
                  />
                </group>
                <group
                  name="particle016"
                  position={[-810.359, 2984.028, -1909.911]}
                  rotation={[1.555, 0.59, -2.682]}
                  scale={252.987}>
                  <mesh
                    name="particle016_leaves_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.particle016_leaves_0.geometry}
                    material={materials.leaves}
                  />
                </group>
                <group
                  name="particle017"
                  position={[-1616.865, 2543.074, 561.138]}
                  rotation={[-1.056, -0.595, 0.87]}
                  scale={298.43}>
                  <mesh
                    name="particle017_leaves_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.particle017_leaves_0.geometry}
                    material={materials.leaves}
                  />
                </group>
                <group
                  name="particle018"
                  position={[-765.52, 2926.413, -1762.237]}
                  rotation={[-1.992, 0.863, -2.793]}
                  scale={185.663}>
                  <mesh
                    name="particle018_leaves_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.particle018_leaves_0.geometry}
                    material={materials.leaves}
                  />
                </group>
                <group
                  name="particle019"
                  position={[-2326.322, 2890.696, 189.742]}
                  rotation={[-0.446, 0.06, -1.112]}
                  scale={219.473}>
                  <mesh
                    name="particle019_leaves_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.particle019_leaves_0.geometry}
                    material={materials.leaves}
                  />
                </group>
                <group
                  name="particle020"
                  position={[-1376.473, 2469.706, 392.918]}
                  rotation={[0.866, 0.821, 0.65]}
                  scale={237.157}>
                  <mesh
                    name="particle020_leaves_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.particle020_leaves_0.geometry}
                    material={materials.leaves}
                  />
                </group>
                <group
                  name="particle021"
                  position={[-862.853, 2704.337, 1751.716]}
                  rotation={[-1.562, -0.537, 0.644]}
                  scale={251.269}>
                  <mesh
                    name="particle021_leaves_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.particle021_leaves_0.geometry}
                    material={materials.leaves}
                  />
                </group>
                <group
                  name="particle022"
                  position={[-899.692, 2701.992, 813.081]}
                  rotation={[-2.419, -0.01, -1.607]}
                  scale={205.205}>
                  <mesh
                    name="particle022_leaves_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.particle022_leaves_0.geometry}
                    material={materials.leaves}
                  />
                </group>
                <group
                  name="particle023"
                  position={[-217.713, 2720.725, 558.732]}
                  rotation={[-1.523, 0.145, 0.221]}
                  scale={300.986}>
                  <mesh
                    name="particle023_leaves_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.particle023_leaves_0.geometry}
                    material={materials.leaves}
                  />
                </group>
                <group
                  name="particle024"
                  position={[-1437.064, 3075.662, -1654.633]}
                  rotation={[-1.381, -0.055, 3.031]}
                  scale={186.082}>
                  <mesh
                    name="particle024_leaves_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.particle024_leaves_0.geometry}
                    material={materials.leaves}
                  />
                </group>
                <group
                  name="particle025"
                  position={[-406.292, 2778.739, 1410.319]}
                  rotation={[0.135, -1.146, -0.016]}
                  scale={168.817}>
                  <mesh
                    name="particle025_leaves_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.particle025_leaves_0.geometry}
                    material={materials.leaves}
                  />
                </group>
                <group
                  name="particle026"
                  position={[-1416.567, 3256.682, -1687.977]}
                  rotation={[2.761, -0.583, 0.172]}
                  scale={177.242}>
                  <mesh
                    name="particle026_leaves_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.particle026_leaves_0.geometry}
                    material={materials.leaves}
                  />
                </group>
                <group
                  name="particle027"
                  position={[-554.308, 2863.007, 679.152]}
                  rotation={[0.679, 1.237, -2.333]}
                  scale={121.691}>
                  <mesh
                    name="particle027_leaves_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.particle027_leaves_0.geometry}
                    material={materials.leaves}
                  />
                </group>
                <group
                  name="particle028"
                  position={[2.832, 2876.565, 1229.37]}
                  rotation={[-2.248, -0.722, -3.074]}
                  scale={138.51}>
                  <mesh
                    name="particle028_leaves_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.particle028_leaves_0.geometry}
                    material={materials.leaves}
                  />
                </group>
                <group
                  name="particle029"
                  position={[93.607, 2794.454, 864.413]}
                  rotation={[-1.307, -1.092, 1.411]}
                  scale={195.629}>
                  <mesh
                    name="particle029_leaves_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.particle029_leaves_0.geometry}
                    material={materials.leaves}
                  />
                </group>
                <group
                  name="particle030"
                  position={[-698.246, 2865.284, 960.414]}
                  rotation={[-1.017, 0.805, -0.712]}
                  scale={157.037}>
                  <mesh
                    name="particle030_leaves_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.particle030_leaves_0.geometry}
                    material={materials.leaves}
                  />
                </group>
                <group
                  name="particle031"
                  position={[-2819.308, 3288.727, 127.181]}
                  rotation={[0.704, 0.272, -1.465]}
                  scale={151.885}>
                  <mesh
                    name="particle031_leaves_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.particle031_leaves_0.geometry}
                    material={materials.leaves}
                  />
                </group>
                <group
                  name="particle032"
                  position={[-761.23, 2895.915, 1742.073]}
                  rotation={[-0.806, -0.311, -1.265]}
                  scale={46.353}>
                  <mesh
                    name="particle032_leaves_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.particle032_leaves_0.geometry}
                    material={materials.leaves}
                  />
                </group>
                <group
                  name="particle033"
                  position={[-944.352, 2922.385, 1503.704]}
                  rotation={[-1.023, -0.229, 1.23]}
                  scale={19.911}>
                  <mesh
                    name="particle033_leaves_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.particle033_leaves_0.geometry}
                    material={materials.leaves}
                  />
                </group>
                <group name="particle034" position={[324.345, 2943.812, 688.659]} scale={0}>
                  <mesh
                    name="particle034_leaves_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.particle034_leaves_0.geometry}
                    material={materials.leaves}
                    position={[0, 0, -4]}
                    scale={0}
                  />
                </group>
                <group name="particle035" position={[-921.933, 2918.776, 837.098]} scale={0}>
                  <mesh
                    name="particle035_leaves_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.particle035_leaves_0.geometry}
                    material={materials.leaves}
                    scale={0}
                  />
                </group>
                <group name="particle036" position={[-553.873, 3361.231, -801.012]} scale={0}>
                  <mesh
                    name="particle036_leaves_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.particle036_leaves_0.geometry}
                    material={materials.leaves}
                    position={[2, 0, 0]}
                    scale={0}
                  />
                </group>
                <group name="particle037" position={[-1944.515, 3269.837, 752.483]} scale={0}>
                  <mesh
                    name="particle037_leaves_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.particle037_leaves_0.geometry}
                    material={materials.leaves}
                    position={[-8, 0, 0]}
                    scale={0}
                  />
                </group>
                <group name="particle038" position={[-2390.156, 3268.063, 735.488]} scale={0}>
                  <mesh
                    name="particle038_leaves_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.particle038_leaves_0.geometry}
                    material={materials.leaves}
                    position={[0, -16, 0]}
                    scale={0}
                  />
                </group>
                <group name="particle039" position={[-2836.547, 3263.79, 551.691]} scale={0}>
                  <mesh
                    name="particle039_leaves_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.particle039_leaves_0.geometry}
                    material={materials.leaves}
                    scale={0}
                  />
                </group>
                <group name="particle040" position={[-1153.881, 3361.231, -1031.08]} scale={0}>
                  <mesh
                    name="particle040_leaves_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.particle040_leaves_0.geometry}
                    material={materials.leaves}
                    scale={0}
                  />
                </group>
                <group name="particle041" position={[-3028.671, 2224.482, -136.117]} scale={0}>
                  <mesh
                    name="particle041_leaves_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.particle041_leaves_0.geometry}
                    material={materials.leaves}
                    position={[0, 0, -0.5]}
                    scale={0}
                  />
                </group>
                <group name="particle042" position={[-913.79, 2013.052, 1138.569]} scale={0}>
                  <mesh
                    name="particle042_leaves_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.particle042_leaves_0.geometry}
                    material={materials.leaves}
                    position={[4, 0, -4]}
                    scale={0}
                  />
                </group>
                <group name="particle043" position={[-3039.798, 2304.69, -590.949]} scale={0}>
                  <mesh
                    name="particle043_leaves_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.particle043_leaves_0.geometry}
                    material={materials.leaves}
                    position={[16, -16, 0]}
                    scale={0}
                  />
                </group>
                <group name="particle044" position={[-1413.687, 2354.914, -1654.065]} scale={0}>
                  <mesh
                    name="particle044_leaves_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.particle044_leaves_0.geometry}
                    material={materials.leaves}
                    position={[8, 16, 0]}
                    scale={0}
                  />
                </group>
                <group name="particle045" position={[-1541.936, 2445.844, -1022.956]} scale={0}>
                  <mesh
                    name="particle045_leaves_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.particle045_leaves_0.geometry}
                    material={materials.leaves}
                    position={[0, -16, 4]}
                    scale={0}
                  />
                </group>
                <group name="particle046" position={[-3654.422, 2422.79, 294.357]} scale={0}>
                  <mesh
                    name="particle046_leaves_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.particle046_leaves_0.geometry}
                    material={materials.leaves}
                    position={[16, 0, 0]}
                    scale={0}
                  />
                </group>
                <group name="particle047" position={[-3054.458, 2362.636, -410.048]} scale={0}>
                  <mesh
                    name="particle047_leaves_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.particle047_leaves_0.geometry}
                    material={materials.leaves}
                    position={[0, 0, 2]}
                    scale={0}
                  />
                </group>
                <group name="particle048" position={[-1809.364, 2238.254, 1133.313]} scale={0}>
                  <mesh
                    name="particle048_leaves_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.particle048_leaves_0.geometry}
                    material={materials.leaves}
                    position={[0, -8, 0]}
                    scale={0}
                  />
                </group>
                <group name="particle049" position={[-857.22, 2194.049, 236.147]} scale={0}>
                  <mesh
                    name="particle049_leaves_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.particle049_leaves_0.geometry}
                    material={materials.leaves}
                    scale={0}
                  />
                </group>
                <group name="particle050" position={[-1483.272, 2222.591, 1028.498]} scale={0}>
                  <mesh
                    name="particle050_leaves_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.particle050_leaves_0.geometry}
                    material={materials.leaves}
                    position={[0, -8, -8]}
                    scale={0}
                  />
                </group>
                <group name="particle051" position={[-937.336, 2313.72, 973.406]} scale={0}>
                  <mesh
                    name="particle051_leaves_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.particle051_leaves_0.geometry}
                    material={materials.leaves}
                    position={[4, -16, -4]}
                    scale={0}
                  />
                </group>
                <group name="particle052" position={[-1241.061, 2202.888, 1263.986]} scale={0}>
                  <mesh
                    name="particle052_leaves_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.particle052_leaves_0.geometry}
                    material={materials.leaves}
                    position={[8, -8, -8]}
                    scale={0}
                  />
                </group>
                <group name="particle053" position={[-2314.272, 2538.749, 160.387]} scale={0}>
                  <mesh
                    name="particle053_leaves_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.particle053_leaves_0.geometry}
                    material={materials.leaves}
                    scale={0}
                  />
                </group>
                <group name="particle054" position={[-509.702, 2284.615, 964.513]} scale={0}>
                  <mesh
                    name="particle054_leaves_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.particle054_leaves_0.geometry}
                    material={materials.leaves}
                    position={[0, 0, -4]}
                    scale={0}
                  />
                </group>
                <group name="particle055" position={[-2980.569, 2720.458, 407.58]} scale={0}>
                  <mesh
                    name="particle055_leaves_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.particle055_leaves_0.geometry}
                    material={materials.leaves}
                    scale={0}
                  />
                </group>
                <group name="particle056" position={[-3069.353, 2646.151, -144.878]} scale={0}>
                  <mesh
                    name="particle056_leaves_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.particle056_leaves_0.geometry}
                    material={materials.leaves}
                    scale={0}
                  />
                </group>
                <group name="particle057" position={[-1243.444, 2778.384, -1195.645]} scale={0}>
                  <mesh
                    name="particle057_leaves_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.particle057_leaves_0.geometry}
                    material={materials.leaves}
                    position={[0, -16, 0]}
                    scale={0}
                  />
                </group>
                <group name="particle058" position={[-752.516, 2547.406, 680.543]} scale={0}>
                  <mesh
                    name="particle058_leaves_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.particle058_leaves_0.geometry}
                    material={materials.leaves}
                    position={[0, -16, -4]}
                    scale={0}
                  />
                </group>
                <group name="particle059" position={[-3034.728, 2782.712, -266.397]} scale={0}>
                  <mesh
                    name="particle059_leaves_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.particle059_leaves_0.geometry}
                    material={materials.leaves}
                    position={[0, -16, 0]}
                    scale={0}
                  />
                </group>
                <group name="particle060" position={[-1447.241, 2909.455, -961.904]} scale={0}>
                  <mesh
                    name="particle060_leaves_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.particle060_leaves_0.geometry}
                    material={materials.leaves}
                    position={[0, 16, 0]}
                    scale={0}
                  />
                </group>
                <group name="particle061" position={[-501.83, 2531.039, 1227.904]} scale={0}>
                  <mesh
                    name="particle061_leaves_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.particle061_leaves_0.geometry}
                    material={materials.leaves}
                    position={[2, 0, 0]}
                    scale={0}
                  />
                </group>
                <group name="particle062" position={[-1471.765, 2992.411, -1324.848]} scale={0}>
                  <mesh
                    name="particle062_leaves_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.particle062_leaves_0.geometry}
                    material={materials.leaves}
                    position={[0, 0, 8]}
                    scale={0}
                  />
                </group>
                <group name="particle063" position={[-884.965, 2963.245, -773.895]} scale={0}>
                  <mesh
                    name="particle063_leaves_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.particle063_leaves_0.geometry}
                    material={materials.leaves}
                    position={[4, -16, 0]}
                    scale={0}
                  />
                </group>
                <group name="particle064" position={[-867.41, 2637.661, 1379.373]} scale={0}>
                  <mesh
                    name="particle064_leaves_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.particle064_leaves_0.geometry}
                    material={materials.leaves}
                    position={[4, 0, 0]}
                    scale={0}
                  />
                </group>
                <group name="particle065" position={[-368.148, 2723.252, 844.201]} scale={0}>
                  <mesh
                    name="particle065_leaves_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.particle065_leaves_0.geometry}
                    material={materials.leaves}
                    scale={0}
                  />
                </group>
                <group name="particle066" position={[-2049.423, 3052.966, -151.975]} scale={0}>
                  <mesh
                    name="particle066_leaves_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.particle066_leaves_0.geometry}
                    material={materials.leaves}
                    scale={0}
                  />
                </group>
                <group name="particle067" position={[-2839.653, 3188.203, -264.061]} scale={0}>
                  <mesh
                    name="particle067_leaves_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.particle067_leaves_0.geometry}
                    material={materials.leaves}
                    position={[16, -16, 0]}
                    scale={0}
                  />
                </group>
                <group name="particle068" position={[-19.994, 2874.47, 615.09]} scale={0}>
                  <mesh
                    name="particle068_leaves_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.particle068_leaves_0.geometry}
                    material={materials.leaves}
                    position={[-0.125, 0, 0]}
                    scale={0}
                  />
                </group>
                <group name="particle069" position={[-224.139, 2806.111, 952.099]} scale={0}>
                  <mesh
                    name="particle069_leaves_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.particle069_leaves_0.geometry}
                    material={materials.leaves}
                    position={[-1, 0, -4]}
                    scale={0}
                  />
                </group>
                <group name="particle070" position={[-2523.754, 3236.757, -376.526]} scale={0}>
                  <mesh
                    name="particle070_leaves_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.particle070_leaves_0.geometry}
                    material={materials.leaves}
                    position={[16, 0, -2]}
                    scale={0}
                  />
                </group>
                <group name="particle071" position={[-1070.031, 3241.295, -741.212]} scale={0}>
                  <mesh
                    name="particle071_leaves_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.particle071_leaves_0.geometry}
                    material={materials.leaves}
                    position={[-4, -16, 0]}
                    scale={0}
                  />
                </group>
                <group name="particle072" position={[-2332.698, 3193.352, 184.08]} scale={0}>
                  <mesh
                    name="particle072_leaves_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.particle072_leaves_0.geometry}
                    material={materials.leaves}
                    position={[16, -16, 0]}
                    scale={0}
                  />
                </group>
                <group name="particle073" position={[-732.753, 3349.882, -1548.192]} scale={0}>
                  <mesh
                    name="particle073_leaves_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.particle073_leaves_0.geometry}
                    material={materials.leaves}
                    position={[0, 0, 8]}
                    scale={0}
                  />
                </group>
                <group name="particle074" position={[-1189.741, 2904.672, 724.613]} scale={0}>
                  <mesh
                    name="particle074_leaves_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.particle074_leaves_0.geometry}
                    material={materials.leaves}
                    scale={0}
                  />
                </group>
                <group
                  name="plom_big"
                  position={[-3139.81, 1567.724, -416.785]}
                  rotation={[-1.239, 0.14, -2.832]}
                  scale={2.792}>
                  <group
                    name="plom_big_Eye1"
                    position={[-4.274, 22.16, -0.242]}
                    rotation={[0.079, 0, Math.PI / 2]}>
                    <mesh
                      name="plom_big_Eye1_character_eyes_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.plom_big_Eye1_character_eyes_0.geometry}
                      material={materials.character_eyes}
                    />
                  </group>
                  <group
                    name="plom_big_Eye2"
                    position={[16.726, 18.857, 0]}
                    rotation={[0.079, 0, Math.PI / 2]}>
                    <mesh
                      name="plom_big_Eye2_character_eyes_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.plom_big_Eye2_character_eyes_0.geometry}
                      material={materials.character_eyes}
                    />
                  </group>
                  <mesh
                    name="plom_big_plom_big_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.plom_big_plom_big_0.geometry}
                    material={materials.plom_big}
                  />
                </group>
                <group name="terrain" position={[-1975.866, 1564.182, -212.216]} scale={100}>
                  <mesh
                    name="terrain_floor_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.terrain_floor_0.geometry}
                    material={materials.floor}
                  />
                </group>
                <group
                  name="trees"
                  position={[-1672.741, 1560.03, -606.562]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}>
                  <mesh
                    name="trees_forest_trees_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.trees_forest_trees_0.geometry}
                    material={materials.forest_trees}
                  />
                </group>
                <group
                  name="water"
                  position={[-2527.764, 1067.392, -1264.758]}
                  scale={[121, 100, 120]}>
                  <mesh
                    name="0"
                    castShadow
                    receiveShadow
                    geometry={nodes['0'].geometry}
                    material={materials.ele_forest_water_dynamic}
                    morphTargetDictionary={nodes['0'].morphTargetDictionary}
                    morphTargetInfluences={nodes['0'].morphTargetInfluences}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/src/assets/test_forest.glb')



