/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 src/assets/habitmon_room.glb --types --output src/threeJS/meshes/RoomGenerated.tsx 
*/

import * as THREE from 'three'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'
import type { ThreeElements } from '@react-three/fiber'
import type { GLTF } from 'three-stdlib'
import roomUrl from '../../assets/habitmon_room.glb?url'

type GLTFResult = GLTF & {
  nodes: {
    clouds: THREE.Mesh
    Cube002: THREE.Mesh
    Cube003: THREE.Mesh
    Cube004: THREE.Mesh
    Cube007: THREE.Mesh
    Cube008: THREE.Mesh
    Cube009: THREE.Mesh
    Cylinder: THREE.Mesh
    Cylinder001: THREE.Mesh
    Cylinder002: THREE.Mesh
    Cube001: THREE.Mesh
    Cube001_1: THREE.Mesh
    Cube001_2: THREE.Mesh
    rug: THREE.Mesh
    window: THREE.Mesh
    window001: THREE.Mesh
  }
  materials: {
    Empty: THREE.MeshStandardMaterial
    Couch: THREE.MeshStandardMaterial
    Cushion: THREE.MeshStandardMaterial
    Shelf: THREE.MeshStandardMaterial
    Desk: THREE.MeshStandardMaterial
    Wood: THREE.MeshStandardMaterial
    Pot: THREE.MeshStandardMaterial
    Walls: THREE.MeshStandardMaterial
    Floor: THREE.MeshStandardMaterial
    Trim: THREE.MeshStandardMaterial
    Rug: THREE.MeshStandardMaterial
  }
}

export function Room(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF(roomUrl) as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <PerspectiveCamera makeDefault={true} far={1000} near={0.1} fov={40.853} position={[0, -0.444, 3.454]} rotation={[-0.205, 0, 0]} />
      <mesh geometry={nodes.clouds.geometry} material={materials.Empty} position={[0, 0.053, -2.551]} rotation={[Math.PI / 2, 0, 0]} scale={0.865} />
      <mesh geometry={nodes.Cube002.geometry} material={materials.Couch} position={[-1.082, -0.827, -2.16]} scale={[0.054, 0.25, 0.517]} />
      <mesh geometry={nodes.Cube003.geometry} material={materials.Cushion} position={[-1.082, -0.827, -2.16]} scale={[0.054, 0.25, 0.517]} />
      <mesh geometry={nodes.Cube004.geometry} material={materials.Cushion} position={[-1.082, -0.827, -2.16]} rotation={[1.281, 0, 0]} scale={[0.046, 0.427, 0.293]} />
      <mesh geometry={nodes.Cube007.geometry} material={materials.Shelf} position={[0, 0.063, -2.354]} scale={[0.588, 0.021, 0.148]} />
      <mesh geometry={nodes.Cube008.geometry} material={materials.Shelf} position={[-0.574, 0.028, -2.354]} scale={[0.014, 0.014, 0.148]} />
      <mesh geometry={nodes.Cube009.geometry} material={materials.Desk} position={[1.674, -0.608, -2.148]} scale={[0.806, 0.03, 0.324]} />
      <mesh geometry={nodes.Cylinder.geometry} material={materials.Wood} position={[-2.011, -1.11, -2.343]} scale={[0.047, 0.074, 0.047]} />
      <mesh geometry={nodes.Cylinder001.geometry} material={materials.Wood} position={[-2.011, -1.11, -1.5]} scale={[0.047, 0.074, 0.047]} />
      <mesh geometry={nodes.Cylinder002.geometry} material={materials.Pot} position={[-2.101, -0.996, -0.069]} scale={0.225} />
      <group scale={[2.5, 1.25, 2.5]}>
        <mesh geometry={nodes.Cube001.geometry} material={materials.Walls} />
        <mesh geometry={nodes.Cube001_1.geometry} material={materials.Floor} />
        <mesh geometry={nodes.Cube001_2.geometry} material={materials.Trim} />
      </group>
      <mesh geometry={nodes.rug.geometry} material={materials.Rug} position={[0, -1.247, 0.306]} scale={[1.773, 1.773, 1.245]} />
      <mesh geometry={nodes.window.geometry} material={materials.Couch} position={[-1.5, 0.417, -2.547]} scale={[2.5, 1.25, 2.5]} />
      <mesh geometry={nodes.window001.geometry} material={materials.Couch} position={[1.492, 0.417, -2.547]} scale={[2.5, 1.25, 2.5]} />
    </group>
  )
}

useGLTF.preload(roomUrl)
