import { GLTF } from 'three-stdlib'
import * as THREE from 'three'

export type GLTFResult = GLTF & {
  nodes: {
    bismo_small_Material001_0: THREE.Mesh
    'bismo_small_Eye1_Default-Material_0': THREE.Mesh
    bismo_small_Eye2_character_eyes_BIGblue_0: THREE.Mesh
    'canyon_mountains02_(3)_rock_0': THREE.Mesh
    Cube_forest_leaves_0: THREE.Mesh
    forest_fox_sleeping_fox_white_new_0: THREE.Mesh
    'forest_grass_03_(9)_grass_0': THREE.Mesh
    particle000_leaves_0: THREE.Mesh
    particle001_leaves_0: THREE.Mesh
    particle002_leaves_0: THREE.Mesh
    particle003_leaves_0: THREE.Mesh
    particle004_leaves_0: THREE.Mesh
    particle005_leaves_0: THREE.Mesh
    particle006_leaves_0: THREE.Mesh
    particle007_leaves_0: THREE.Mesh
    particle008_leaves_0: THREE.Mesh
    particle009_leaves_0: THREE.Mesh
    particle010_leaves_0: THREE.Mesh
    particle011_leaves_0: THREE.Mesh
    particle012_leaves_0: THREE.Mesh
    particle013_leaves_0: THREE.Mesh
    particle014_leaves_0: THREE.Mesh
    particle015_leaves_0: THREE.Mesh
    particle016_leaves_0: THREE.Mesh
    particle017_leaves_0: THREE.Mesh
    particle018_leaves_0: THREE.Mesh
    particle019_leaves_0: THREE.Mesh
    particle020_leaves_0: THREE.Mesh
    particle021_leaves_0: THREE.Mesh
    particle022_leaves_0: THREE.Mesh
    particle023_leaves_0: THREE.Mesh
    particle024_leaves_0: THREE.Mesh
    particle025_leaves_0: THREE.Mesh
    particle026_leaves_0: THREE.Mesh
    particle027_leaves_0: THREE.Mesh
    particle028_leaves_0: THREE.Mesh
    particle029_leaves_0: THREE.Mesh
    particle030_leaves_0: THREE.Mesh
    particle031_leaves_0: THREE.Mesh
    particle032_leaves_0: THREE.Mesh
    particle033_leaves_0: THREE.Mesh
    particle034_leaves_0: THREE.Mesh
    particle035_leaves_0: THREE.Mesh
    particle036_leaves_0: THREE.Mesh
    particle037_leaves_0: THREE.Mesh
    particle038_leaves_0: THREE.Mesh
    particle039_leaves_0: THREE.Mesh
    particle040_leaves_0: THREE.Mesh
    particle041_leaves_0: THREE.Mesh
    particle042_leaves_0: THREE.Mesh
    particle043_leaves_0: THREE.Mesh
    particle044_leaves_0: THREE.Mesh
    particle045_leaves_0: THREE.Mesh
    particle046_leaves_0: THREE.Mesh
    particle047_leaves_0: THREE.Mesh
    particle048_leaves_0: THREE.Mesh
    particle049_leaves_0: THREE.Mesh
    particle050_leaves_0: THREE.Mesh
    particle051_leaves_0: THREE.Mesh
    particle052_leaves_0: THREE.Mesh
    particle053_leaves_0: THREE.Mesh
    particle054_leaves_0: THREE.Mesh
    particle055_leaves_0: THREE.Mesh
    particle056_leaves_0: THREE.Mesh
    particle057_leaves_0: THREE.Mesh
    particle058_leaves_0: THREE.Mesh
    particle059_leaves_0: THREE.Mesh
    particle060_leaves_0: THREE.Mesh
    particle061_leaves_0: THREE.Mesh
    particle062_leaves_0: THREE.Mesh
    particle063_leaves_0: THREE.Mesh
    particle064_leaves_0: THREE.Mesh
    particle065_leaves_0: THREE.Mesh
    particle066_leaves_0: THREE.Mesh
    particle067_leaves_0: THREE.Mesh
    particle068_leaves_0: THREE.Mesh
    particle069_leaves_0: THREE.Mesh
    particle070_leaves_0: THREE.Mesh
    particle071_leaves_0: THREE.Mesh
    particle072_leaves_0: THREE.Mesh
    particle073_leaves_0: THREE.Mesh
    particle074_leaves_0: THREE.Mesh
    plom_big_Eye1_character_eyes_0: THREE.Mesh
    plom_big_Eye2_character_eyes_0: THREE.Mesh
    plom_big_plom_big_0: THREE.Mesh
    terrain_floor_0: THREE.Mesh
    trees_forest_trees_0: THREE.Mesh
    '0': THREE.Mesh
  }
  materials: {
    'Material.001': THREE.MeshStandardMaterial
    'Default-Material': THREE.MeshStandardMaterial
    character_eyes_BIGblue: THREE.MeshStandardMaterial
    rock: THREE.MeshStandardMaterial
    forest_leaves: THREE.MeshStandardMaterial
    fox_white_new: THREE.MeshStandardMaterial
    grass: THREE.MeshStandardMaterial
    leaves: THREE.MeshStandardMaterial
    character_eyes: THREE.MeshStandardMaterial
    plom_big: THREE.MeshStandardMaterial
    floor: THREE.MeshStandardMaterial
    forest_trees: THREE.MeshStandardMaterial
    ele_forest_water_dynamic: THREE.MeshStandardMaterial
  }
}
